CREATE TABLE DM_99_CO_RENTAL_LISTING_LINKS_T
(
LINK TEXT UNIQUE
)
;

CREATE TABLE DM_99_CO_RENTAL_LISTINGS_LINKS_USED_T
(
LINK TEXT UNIQUE
)
;

DROP TABLE DM_99_CO_RENTAL_LISTING_LINKS_T;
DROP TABLE DM_99_CO_RENTAL_LISTINGS_LINKS_USED_T;
