CREATE TABLE DM_99_CO_RENTAL_LISTING_PROPERTY_T
(
PROPERTY_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
NAME TEXT UNIQUE,
TYPE TEXT,
UNIT_TYPES TEXT,
UNIT_CNT TEXT,
BUILD_YEAR TEXT,
GOV_LEASE TEXT,
DEVELOPER_NAME TEXT,
NEIGHBOURHOOD TEXT
)
;

DROP TABLE DM_99_CO_RENTAL_LISTING_PROPERTY_T;
