
CREATE TABLE DM_99_CO_RENTAL_LISTING_ADD_INFO_T
(
LISTING_ID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
LEASE_START TEXT,
LEASE_TYPE TEXT,
LEASE_FACING TEXT,
LEASE_FURNITURE TEXT,
PROPERTY_ID INTEGER
)
;

DROP TABLE DM_99_CO_RENTAL_LISTING_ADD_INFO_T;

COMMIT;